### ISSUE TITLE
sitewide: footer issues (see below)

### ISSUE THREAD

**Issue by joebachana** [DrupalCamp-NYC/dcnyc16#38]
1. "powered by drupal 8" smaller font and block moves to left
2. "Powered by pantheon" Logo made smaller and moved to center
3. "Connect with us" block head made smaller and moved to the right
4. whole footer placed in a separate mortise below "premium sponsor" block

**Comment by hhilaire** [comment]
4. whole footer placed in a separate mortise below "premium sponsor" block
You need to put the sponsor block in the region 'content' instead of 'footer' + configure the view so the block doesn't appear if empty. Can someone do that on the main build? Not sure I can access it with the credentials I have.

**Comment by joebachana** [comment]
fixed except issue with premium sponsor block (will create new ticket)
